MEM and WB Stages
CompArchBDZ/Lab3 pull request #13
Opened 2016-11-10 16:45 UTC by bishiguro

2016-11-10 17:16 UTC, hdavidzhu requested changes

2016-11-10 17:16 UTC, hdavidzhu commented on Makefile
> +build-memwb_reg:
This should not exist?

2016-11-10 17:16 UTC, hdavidzhu commented on cpu.v
> +`define AND and #330
Let's keep the delays out for now.

2016-11-10 17:16 UTC, hdavidzhu commented on cpu.v
> +		.regWrite_EX(), // need regWrite_EX
Normally, I like to start things that need to be complete with `TODO:`. This way, I can quickly search through the codebase and find things that still needs to be done.

2016-11-10 17:16 UTC, hdavidzhu commented on gate_ex_mem.v
> +  input clk,
I've actually been following your old pattern, where `clk` lies between the `output`s and `input`s. This is because `clk` is an input in itself.

2016-11-10 17:16 UTC, hdavidzhu commented on mux2Input.v
> +`define OR or #330
Again, let's create these gates in a `gates.v` file, and then not delay them until later.

2016-11-10 17:16 UTC, hdavidzhu commented on mux2Input.v
> +`define OR or #330
You can use the `ifndef` pattern. We can look at that together.

2016-11-11 16:12 UTC, hdavidzhu commented
@bishiguro Are you ready for another review? If so, ping me on Slack.

2016-11-11 16:54 UTC, hdavidzhu requested changes

2016-11-11 16:54 UTC, hdavidzhu commented on cpu.v
> +		wire memToReg_WB;
some weird indents over here

2016-11-11 16:54 UTC, hdavidzhu commented on cpu.v
> +		wire [31:0] readData_WB;
☝️

2016-11-11 16:54 UTC, hdavidzhu commented on datamemory.v
> +          memory[address] <= dataIn;
i think this can be better with `begin` and `end` to never run into bugs

2016-11-11 16:54 UTC, hdavidzhu commented on datamemory.v
> +      dataOut <= memory[address];
nice!

2016-11-11 16:54 UTC, hdavidzhu commented on gates.v
> +`define OR or
also wrap this using the `ifndef` pattern. What verilog does is duplicate code. (It's the worst.) if you have those if else chunks, the console won't throw errors later

2016-11-11 16:54 UTC, hdavidzhu commented on mux2Input.v
> +module mux2Input
also check out `Parameter Override during instantiating.` @ http://www.asic-world.com/verilog/para_modules1.html

`secret_number #(11) U0();`

The good thing about parameters is that we can define them outside of the module. This works fine tho, if we do have 1 input muxes, we can use the same component.

2016-11-12 21:49 UTC, bishiguro commented on datamemory.v
> +          memory[address] <= dataIn;
I'm not exactly sure what this means - the always block has a begin/end?

2016-11-12 23:31 UTC, hdavidzhu commented on datamemory.v
> +          memory[address] <= dataIn;
```
if (writeEnable) begin
  memory[address] <= dataIn;
end
```

2016-11-13 17:33 UTC, hdavidzhu approved these changes

2016-11-13 17:33 UTC, hdavidzhu commented on gates.v
> +`endif
This works, what I meant is something different, I can update that

2016-11-13 17:33 UTC, hdavidzhu commented on mux2Input.v
> +	mux2Input #(32, 32) U0(.out(out),
you could simply inline this, no need to make another module

2016-11-13 18:47 UTC, merged